services:
  - docker

before_install:
  - docker build -t sloppy/oh-hai:travis .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push sloppy/oh-hai:travis
  - docker run -d sloppy/oh-hai:travis

script:
  - docker ps | grep -q sloppy

after_success:
  - apt-get install httpie jq
  - hmod +x sloppy
  - chmod +x deploy.sh
  - ./deploy.sh
  - exit $?

notifications:
  email:
    recipients:
      - info@sloppy.io
    on_success: never
    on_failure: always
