services:
  - docker

before_install:
  - docker build -t sloppy/oh-hai:travis .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push sloppy/oh-hai:travis
  - docker run -d sloppy/oh-hai:travis

script:
  - docker ps | grep -q sloppy

after_success:
  - curl -L https://files.sloppy.io/sloppy-`uname -s`-`uname -m` > sloppy
  - chmod +x sloppy
  - ./sloppy show $SLOPPY_PROJECT;if [ $? -eq 0 ]; then sloppy change -var domain:$DOMAIN $SLOPPY_PROJECT $SLOPPY_FILE; else sloppy start -var domain:$DOMAIN $SLOPPY_FILE; fi
  - exit $?

notifications:
  email:
    recipients:
      - info@sloppy.io
    on_success: never
    on_failure: always
